project_id = "gjlxuvcfoqjhwzcmpaju"

[functions.grammify]
verify_jwt = false

[functions.pollinations-chat]
verify_jwt = false

[functions.pollinations-tts]
verify_jwt = false

[functions.pollinations-image]
verify_jwt = false

[functions.youtube-explain]
verify_jwt = false

[functions.track-session]
verify_jwt = false

[functions.log-message]
verify_jwt = false

[functions.update-session-activity]
verify_jwt = false

[functions.owner-dashboard]
verify_jwt = false

[functions.image-upscale]
verify_jwt = false

[functions.create-note]
verify_jwt = false

[functions.get-note]
verify_jwt = false

[functions.check-note-slug]
verify_jwt = false

[functions.notes-dashboard]
verify_jwt = false

[functions.generate-suggestions]
verify_jwt = false

[functions.pollinations-image-v2]
verify_jwt = false

[functions.pollinations-video]
verify_jwt = false

[functions.video-gen]
verify_jwt = false

[functions.book-chat-stream]
verify_jwt = false

[functions.fetch-emails]
verify_jwt = false

[functions.send-email-smtp]
verify_jwt = false

[functions.giyaat-proxy]
verify_jwt = false

[functions.enhance-video-prompt]
verify_jwt = false

[functions.web-gen]
verify_jwt = false

[functions.apifree-chat]
verify_jwt = false

[functions.image-gen-multi]
verify_jwt = false
