import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import Header from '@/components/Header';

const Terms = () => {
  useEffect(() => {
    document.title = "Terms of Service - FARABI.me";
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute('content', 'Terms of Service for FARABI.me - AI-powered educational chatbot platform.');
    }
  }, []);

  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-br from-background via-background to-accent/5">
      <Header />
      <main className="flex-1 container max-w-4xl mx-auto px-4 md:px-6 py-8 md:py-12">
        <Card className="border-2 md:border-4 p-6 md:p-8">
          <div className="mb-6">
            <Button
              variant="ghost"
              size="sm"
              asChild
              className="text-base md:text-lg mb-4"
            >
              <Link to="/">
                <ArrowLeft className="mr-2 h-5 w-5" />
                Back to Chat
              </Link>
            </Button>
            <h1 className="text-3xl md:text-4xl font-bold mb-2">Terms of Service</h1>
            <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
          </div>

          <div className="space-y-6 text-foreground/90">
            <section>
              <h2 className="text-2xl font-semibold mb-3 text-foreground">1. Acceptance of Terms</h2>
              <p>
                By accessing and using FARABI.me, you accept and agree to be bound by these Terms of Service. 
                If you do not agree to these terms, please do not use our service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3 text-foreground">2. Service Description</h2>
              <p>
                FARABI.me provides an AI-powered educational chatbot platform that offers various features including:
              </p>
              <ul className="list-disc ml-6 mt-2 space-y-1">
                <li>AI chat assistance with multiple response modes</li>
                <li>Image generation capabilities</li>
                <li>MCQ quiz generation</li>
                <li>Flashcard creation</li>
                <li>YouTube video explanations</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3 text-foreground">3. User Responsibilities</h2>
              <p className="mb-2">You agree to:</p>
              <ul className="list-disc ml-6 space-y-1">
                <li>Use the service for lawful educational purposes only</li>
                <li>Not attempt to abuse, exploit, or disrupt the service</li>
                <li>Not use the service to generate harmful, illegal, or inappropriate content</li>
                <li>Not attempt to reverse engineer or extract proprietary information</li>
                <li>Respect intellectual property rights</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3 text-foreground">4. Anonymous Usage</h2>
              <p>
                FARABI.me operates without requiring user accounts or authentication. We track anonymous usage data 
                including chat messages, session information, and country-based analytics for service improvement. 
                This data is temporary and not linked to personally identifiable information.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3 text-foreground">5. AI-Generated Content</h2>
              <p>
                All content generated by our AI systems, including text responses, images, quizzes, and flashcards, 
                is provided "as is" without warranties. The AI can make mistakes, and users should verify important 
                information from reliable sources. We are not responsible for decisions made based on AI-generated content.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3 text-foreground">6. Content Storage</h2>
              <p>
                Chat history, generated content, and user preferences are stored locally in your browser using localStorage. 
                We do not permanently store your conversations on our servers. Backend analytics data is temporary and 
                designed for real-time monitoring only.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3 text-foreground">7. Intellectual Property</h2>
              <p>
                The FARABI.me platform, including its design, features, and branding, is proprietary. Content you generate 
                using our service is yours, but we retain rights to aggregate anonymized usage data for service improvement.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3 text-foreground">8. Service Availability</h2>
              <p>
                We strive to maintain service availability but do not guarantee uninterrupted access. We reserve the right 
                to modify, suspend, or discontinue any part of the service at any time without prior notice.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3 text-foreground">9. Limitation of Liability</h2>
              <p>
                FARABI.me is provided free of charge for educational purposes. We are not liable for any damages, losses, 
                or issues arising from your use of the service. Use at your own risk.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3 text-foreground">10. Third-Party Services</h2>
              <p>
                Our platform integrates with third-party AI services (Pollinations AI) and infrastructure providers. 
                We are not responsible for the availability, accuracy, or policies of these external services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3 text-foreground">11. Modifications to Terms</h2>
              <p>
                We reserve the right to modify these Terms of Service at any time. Continued use of the service after 
                changes constitutes acceptance of the modified terms. Check this page regularly for updates.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3 text-foreground">12. Contact Information</h2>
              <p>
                For questions or concerns about these Terms of Service, please contact us through the chat interface 
                or visit our main website for additional contact options.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3 text-foreground">13. Governing Law</h2>
              <p>
                These Terms of Service are governed by applicable laws. Any disputes will be resolved in accordance 
                with the jurisdiction where the service is operated.
              </p>
            </section>
          </div>
        </Card>
      </main>
    </div>
  );
};

export default Terms;
